### ISSUE TITLE
src code for kdmoncat.glitch.me ?

### ISSUE THREAD

**Issue by 100ideas** [statebox/awesome-applied-ct#2]
I'm interested in reviewing the purescript src code for the [kdmoncat](http://kdmoncat.glitch.me/) example, if it's available. Thanks!

https://github.com/statebox/awesome-applied-category-theory/blame/master/README.md#L88

**Comment by epost** [comment]
Hi Mac, thanks for your interest! We plan to open source the brick diagram editor soonish. No exact date yet, but you might want to keep an eye on https://twitter.com/statebox.

**Comment by 100ideas** [comment]
cool, looking forward to it... and any other learning playground goodies in the pipeline :)

ah also saw a comment re: this issue here https://twitter.com/wires_wires/status/1176453424591908865
